alg_name: "FT"
model_name: "stanford-crfm/BioMedLM"
device: 0

layers: [14]
num_steps: 25
batch_size: 1
max_length: 250
lr: 5e-4
weight_decay: 0
kl_factor: 0
norm_constraint: 5e-5
rewrite_module_tmp: "transformer.h.{}.mlp.c_proj"
layer_module_tmp: "transformer.h.{}"
mlp_module_tmp: "transformer.h.{}.mlp"
attn_module_tmp: "transformer.h.{}.attn"
ln_f_module: "transformer.ln_f"
lm_head_module: "transformer.wte"
model_parallel: false